name: 'Another GitHub Action'

on:
  push:
    branches:
      - 'feature/test'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pwd
          chmod +x ./.github/scripts/script.sh
          bash ./.github/scripts/script.sh
